// <auto-generated />
using System;
using EMAC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMAC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251130123652_initialCreate3")]
    partial class initialCreate3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMAC.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("EMAC.Models.InitialReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CustomerApproval")
                        .HasColumnType("bit");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EstimatedTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaultDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredSpareParts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicianNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkshopTicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopTicketId");

                    b.ToTable("InitialReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 29, 14, 36, 51, 471, DateTimeKind.Local).AddTicks(5753),
                            CustomerApproval = false,
                            EstimatedCost = 850m,
                            EstimatedTime = "3 أيام",
                            FaultDescription = "تلف في الكومبريسور ونقص فريون",
                            RequiredSpareParts = "كومبريسور جديد، غاز فريون",
                            TechnicianNotes = "يحتاج تنظيف شامل للوحدة الداخلية",
                            WorkshopTicketId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 26, 14, 36, 51, 471, DateTimeKind.Local).AddTicks(5761),
                            CustomerApproval = true,
                            EstimatedCost = 350m,
                            EstimatedTime = "يوم واحد",
                            FaultDescription = "عطل في الثرموستات",
                            RequiredSpareParts = "ثرموستات أصلي",
                            TechnicianNotes = "تم الاختبار بنجاح",
                            WorkshopTicketId = 2
                        });
                });

            modelBuilder.Entity("EMAC.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LaborCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SparePartsCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WorkshopTicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopTicketId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPaid = true,
                            IssuedAt = new DateTime(2025, 11, 27, 14, 36, 51, 471, DateTimeKind.Local).AddTicks(5823),
                            LaborCost = 150m,
                            PaymentMethod = "CreditCard",
                            SparePartsCost = 200m,
                            TaxAmount = 52.5m,
                            TotalAmount = 402.5m,
                            WorkshopTicketId = 2
                        });
                });

            modelBuilder.Entity("EMAC.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArabicName = "صيانة مكيفات سبليت/شباك",
                            Code = "ac_maint",
                            Description = "غسيل وتنظيف وإصلاح أعطال",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            ArabicName = "صيانة تكييف مركزي",
                            Code = "central_maint",
                            Description = "للمجمعات والفلل",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            ArabicName = "تمديد مواسير نحاس",
                            Code = "pipe_extension",
                            Description = "تأسيس وتمديد",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            ArabicName = "صيانة ثلاجات ومجمدات",
                            Code = "fridge_repair",
                            Description = "إصلاح منزلي وتجاري",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            ArabicName = "صيانة غسالات",
                            Code = "wash_repair",
                            Description = "أوتوماتيك وعادي",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            ArabicName = "صيانة أفران وميكروويف",
                            Code = "oven_repair",
                            Description = "كهرباء وغاز",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            ArabicName = "تركيب/صيانة غرف تبريد",
                            Code = "fridge_room_install",
                            Description = "مخازن التبريد",
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            ArabicName = "صيانة تكييف سيارات مبردة",
                            Code = "car_ac",
                            Description = "شاحنات النقل المبرد",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("EMAC.Models.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TechnicianId");

                    b.ToTable("ServiceRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2025, 11, 28, 14, 36, 51, 471, DateTimeKind.Local).AddTicks(4081),
                            CreatedAt = new DateTime(2025, 11, 28, 14, 36, 51, 471, DateTimeKind.Local).AddTicks(4087),
                            CustomerName = "عبدالله محمد",
                            DeviceCode = "DEV-AC-101",
                            Location = "hassa",
                            PhoneNumber = "0501234567",
                            ProblemDescription = "المكيف لا يبرد ويصدر صوت عالي",
                            RequestNumber = "REQ-20251120-1001",
                            ServiceType = "ac_maint",
                            Status = "InWorkshop",
                            TimeSlot = "09:00 ص"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2025, 11, 29, 14, 36, 51, 471, DateTimeKind.Local).AddTicks(4093),
                            CreatedAt = new DateTime(2025, 11, 29, 14, 36, 51, 471, DateTimeKind.Local).AddTicks(4096),
                            CustomerName = "شركة النقل السريع",
                            DeviceCode = "DEV-CA-205",
                            Location = "dammam",
                            PhoneNumber = "0559876543",
                            ProblemDescription = "صيانة دورية لأسطول الشاحنات المبردة",
                            RequestNumber = "REQ-20251121-2005",
                            ServiceType = "car_ac",
                            Status = "Confirmed",
                            TimeSlot = "02:00 م"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2025, 11, 25, 14, 36, 51, 471, DateTimeKind.Local).AddTicks(4892),
                            CreatedAt = new DateTime(2025, 11, 25, 14, 36, 51, 471, DateTimeKind.Local).AddTicks(4895),
                            CustomerName = "سارة أحمد",
                            DeviceCode = "DEV-FR-304",
                            Location = "riyadh",
                            PhoneNumber = "0561112233",
                            ProblemDescription = "الثلاجة لا تعمل نهائياً",
                            RequestNumber = "REQ-20251115-3040",
                            ServiceType = "fridge_repair",
                            Status = "Closed",
                            TimeSlot = "10:00 ص"
                        });
                });

            modelBuilder.Entity("EMAC.Models.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoveredRegions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingHoursEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingHoursStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoveredRegions = "hassa,dammam",
                            FullName = "أحمد علي",
                            Specialty = "ac_maint",
                            WorkingHoursEnd = "18:00",
                            WorkingHoursStart = "08:00"
                        },
                        new
                        {
                            Id = 2,
                            CoveredRegions = "riyadh,hassa",
                            FullName = "محمد سامي",
                            Specialty = "fridge_repair",
                            WorkingHoursEnd = "18:00",
                            WorkingHoursStart = "08:00"
                        },
                        new
                        {
                            Id = 3,
                            CoveredRegions = "all",
                            FullName = "فريق المشاريع (أ)",
                            Specialty = "central_maint",
                            WorkingHoursEnd = "18:00",
                            WorkingHoursStart = "08:00"
                        },
                        new
                        {
                            Id = 4,
                            CoveredRegions = "hassa,dammam,riyadh,other,all",
                            FullName = "فني عام (للتجربة)",
                            Specialty = "General",
                            WorkingHoursEnd = "18:00",
                            WorkingHoursStart = "08:00"
                        });
                });

            modelBuilder.Entity("EMAC.Models.WorkshopTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accessories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicalCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId");

                    b.ToTable("WorkshopTickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accessories = "ريموت كنترول",
                            DeviceCode = "WS-1122-5544",
                            DeviceModel = "مكيف سبليت جنرال 24 وحدة",
                            PhysicalCondition = "خدوش بسيطة في الغطاء الخارجي",
                            ReceivedAt = new DateTime(2025, 11, 28, 14, 36, 51, 471, DateTimeKind.Local).AddTicks(5565),
                            SerialNumber = "SN-99887766",
                            ServiceRequestId = 1,
                            Status = "Inspected"
                        },
                        new
                        {
                            Id = 2,
                            Accessories = "بدون",
                            DeviceCode = "WS-1115-3322",
                            DeviceModel = "ثلاجة سامسونج 20 قدم",
                            PhysicalCondition = "سليمة",
                            ReceivedAt = new DateTime(2025, 11, 25, 14, 36, 51, 471, DateTimeKind.Local).AddTicks(5581),
                            SerialNumber = "SN-11223344",
                            ServiceRequestId = 3,
                            Status = "Closed"
                        });
                });

            modelBuilder.Entity("EMAC.Models.InitialReport", b =>
                {
                    b.HasOne("EMAC.Models.WorkshopTicket", "WorkshopTicket")
                        .WithMany()
                        .HasForeignKey("WorkshopTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkshopTicket");
                });

            modelBuilder.Entity("EMAC.Models.Invoice", b =>
                {
                    b.HasOne("EMAC.Models.WorkshopTicket", "WorkshopTicket")
                        .WithMany()
                        .HasForeignKey("WorkshopTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkshopTicket");
                });

            modelBuilder.Entity("EMAC.Models.ServiceRequest", b =>
                {
                    b.HasOne("EMAC.Models.Technician", "AssignedTechnician")
                        .WithMany()
                        .HasForeignKey("TechnicianId");

                    b.Navigation("AssignedTechnician");
                });

            modelBuilder.Entity("EMAC.Models.WorkshopTicket", b =>
                {
                    b.HasOne("EMAC.Models.ServiceRequest", "ServiceRequest")
                        .WithMany()
                        .HasForeignKey("ServiceRequestId");

                    b.Navigation("ServiceRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
