// <auto-generated />
using System;
using EMAC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMAC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207084116_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMAC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "ac_cat.png",
                            Name = "مكيفات"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "kitchen_cat.png",
                            Name = "أجهزة مطبخ"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "wash_cat.png",
                            Name = "غسالات ومجففات"
                        },
                        new
                        {
                            Id = 4,
                            Name = "مكيفات سبليت",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "مكيفات شباك",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "مكيفات دولابي",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "ثلاجات",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "أفران",
                            ParentId = 2
                        });
                });

            modelBuilder.Entity("EMAC.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("EMAC.Models.InitialReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CustomerApproval")
                        .HasColumnType("bit");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EstimatedTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaultDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredSpareParts")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicianNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkshopTicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopTicketId");

                    b.ToTable("InitialReports");
                });

            modelBuilder.Entity("EMAC.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LaborCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SparePartsCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WorkshopTicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopTicketId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("EMAC.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SizeOrCapacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Gree",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 12, 7, 10, 41, 14, 61, DateTimeKind.Local).AddTicks(9167),
                            Description = "مكيف عالي الكفاءة، توزيع هواء رباعي، موفر للطاقة.",
                            ImageUrl = "gree_split.png",
                            IsFeatured = true,
                            Name = "مكيف جري سبليت 18000 وحدة - بارد",
                            OldPrice = 2450m,
                            Price = 2100m,
                            SizeOrCapacity = "18000 BTU"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "LG",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 12, 7, 10, 41, 14, 61, DateTimeKind.Local).AddTicks(9222),
                            Description = "كمبروسر قوي، تبريد سريع، ضمان 7 سنوات.",
                            ImageUrl = "lg_window.png",
                            IsFeatured = false,
                            Name = "مكيف إل جي شباك 24000 وحدة",
                            OldPrice = 2000m,
                            Price = 1850m,
                            SizeOrCapacity = "24000 BTU"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Royal",
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 12, 7, 10, 41, 14, 61, DateTimeKind.Local).AddTicks(9226),
                            Description = "12 برنامج للطهي، وعاء غير لاصق، مؤقت ذكي.",
                            ImageUrl = "royal_pot.png",
                            IsFeatured = true,
                            Name = "حلة ضغط كهربائية رويال 10 لتر",
                            OldPrice = 299m,
                            Price = 229m,
                            SizeOrCapacity = "10 Liter"
                        });
                });

            modelBuilder.Entity("EMAC.Models.ServiceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArabicName = "صيانة مكيفات سبليت/شباك",
                            Code = "ac_maint",
                            Description = "غسيل وتنظيف وإصلاح أعطال",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            ArabicName = "صيانة تكييف مركزي",
                            Code = "central_maint",
                            Description = "للمجمعات والفلل",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            ArabicName = "تمديد مواسير نحاس",
                            Code = "pipe_extension",
                            Description = "تأسيس وتمديد",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            ArabicName = "صيانة ثلاجات ومجمدات",
                            Code = "fridge_repair",
                            Description = "إصلاح منزلي وتجاري",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            ArabicName = "صيانة غسالات",
                            Code = "wash_repair",
                            Description = "أوتوماتيك وعادي",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            ArabicName = "صيانة أفران وميكروويف",
                            Code = "oven_repair",
                            Description = "كهرباء وغاز",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            ArabicName = "تركيب/صيانة غرف تبريد",
                            Code = "fridge_room_install",
                            Description = "مخازن التبريد",
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            ArabicName = "صيانة تكييف سيارات مبردة",
                            Code = "car_ac",
                            Description = "شاحنات النقل المبرد",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("EMAC.Models.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProblemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("int");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TechnicianId");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("EMAC.Models.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoveredRegions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingHoursEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingHoursStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoveredRegions = "hassa,dammam",
                            FullName = "أحمد علي",
                            Specialty = "ac_maint",
                            WorkingHoursEnd = "18:00",
                            WorkingHoursStart = "08:00"
                        },
                        new
                        {
                            Id = 2,
                            CoveredRegions = "riyadh,hassa",
                            FullName = "محمد سامي",
                            Specialty = "fridge_repair",
                            WorkingHoursEnd = "18:00",
                            WorkingHoursStart = "08:00"
                        },
                        new
                        {
                            Id = 3,
                            CoveredRegions = "all",
                            FullName = "فريق المشاريع (أ)",
                            Specialty = "central_maint",
                            WorkingHoursEnd = "18:00",
                            WorkingHoursStart = "08:00"
                        },
                        new
                        {
                            Id = 4,
                            CoveredRegions = "hassa,dammam,riyadh,other,all",
                            FullName = "فني عام (للتجربة)",
                            Specialty = "General",
                            WorkingHoursEnd = "18:00",
                            WorkingHoursStart = "08:00"
                        });
                });

            modelBuilder.Entity("EMAC.Models.WorkshopTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accessories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicalCondition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId");

                    b.ToTable("WorkshopTickets");
                });

            modelBuilder.Entity("EMAC.Models.Category", b =>
                {
                    b.HasOne("EMAC.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("EMAC.Models.InitialReport", b =>
                {
                    b.HasOne("EMAC.Models.WorkshopTicket", "WorkshopTicket")
                        .WithMany()
                        .HasForeignKey("WorkshopTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkshopTicket");
                });

            modelBuilder.Entity("EMAC.Models.Invoice", b =>
                {
                    b.HasOne("EMAC.Models.WorkshopTicket", "WorkshopTicket")
                        .WithMany()
                        .HasForeignKey("WorkshopTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkshopTicket");
                });

            modelBuilder.Entity("EMAC.Models.Product", b =>
                {
                    b.HasOne("EMAC.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EMAC.Models.ServiceRequest", b =>
                {
                    b.HasOne("EMAC.Models.Technician", "AssignedTechnician")
                        .WithMany()
                        .HasForeignKey("TechnicianId");

                    b.Navigation("AssignedTechnician");
                });

            modelBuilder.Entity("EMAC.Models.WorkshopTicket", b =>
                {
                    b.HasOne("EMAC.Models.ServiceRequest", "ServiceRequest")
                        .WithMany()
                        .HasForeignKey("ServiceRequestId");

                    b.Navigation("ServiceRequest");
                });

            modelBuilder.Entity("EMAC.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
